"""Phase 3 metadata registry — stable-id-v1 aligned SQLite foundation.

Target authoritative architecture for identity + lifecycle. Production
authority switch is NOT activated; APIs require an explicit DB path.

Does not open production DBs or create ``.rag_state`` on import.
"""

from __future__ import annotations

from rag_engine.metadata_registry.connection import (
    connect_registry,
    normalize_db_path,
    open_registry,
)
from rag_engine.metadata_registry.exceptions import (
    DowngradeNotAllowedError,
    ExistingDatabaseError,
    ExplicitPathRequiredError,
    InvalidDatabasePathError,
    LifecycleError,
    LifecycleTransitionError,
    MissingDatabaseError,
    MigrationError,
    ParentDirectoryMissingError,
    RegistryConflictError,
    RegistryError,
    RegistryIntegrityError,
    RegistryValidationError,
    UnknownSchemaVersionError,
)
from rag_engine.metadata_registry.lifecycle import (
    LIFECYCLE_ACTIVE,
    LIFECYCLE_ARCHIVED,
    LIFECYCLE_DUPLICATE,
    LIFECYCLE_REPLACED,
    LIFECYCLE_STATES,
    LIFECYCLE_SUPERSEDED,
    LIFECYCLE_WITHDRAWN,
    RELATION_DUPLICATE_OF,
    RELATION_REPLACES,
    RELATION_SUPERSEDES,
    RELATION_TYPES,
    activate_revision,
    archive_revision,
    get_active_revision,
    get_lifecycle_history,
    get_relations,
    get_revision_status,
    mark_duplicate,
    replace_revision,
    set_revision_status,
    supersede_revision,
    transition_matrix,
    withdraw_revision,
)
from rag_engine.metadata_registry.migrations import (
    current_schema_version,
    foreign_keys_enabled,
    get_schema_version,
    initialize_registry,
    migrate_connection,
)
from rag_engine.metadata_registry.paths import (
    APPROVED_PRODUCTION_FILENAME,
    production_registry_dir,
    production_registry_path,
)
from rag_engine.metadata_registry.repository import (
    RegistryRepository,
    make_source_file_id,
    register_chunk,
    register_document_lifecycle,
    register_document_version,
    register_source_file,
    register_subject,
    register_vector_mapping,
    registry_transaction,
)
from rag_engine.metadata_registry.schema import (
    CURRENT_SCHEMA_VERSION,
    REQUIRED_TABLES,
    SCHEMA_SQL,
)

__all__ = [
    "APPROVED_PRODUCTION_FILENAME",
    "CURRENT_SCHEMA_VERSION",
    "DowngradeNotAllowedError",
    "ExistingDatabaseError",
    "ExplicitPathRequiredError",
    "InvalidDatabasePathError",
    "LIFECYCLE_ACTIVE",
    "LIFECYCLE_ARCHIVED",
    "LIFECYCLE_DUPLICATE",
    "LIFECYCLE_REPLACED",
    "LIFECYCLE_STATES",
    "LIFECYCLE_SUPERSEDED",
    "LIFECYCLE_WITHDRAWN",
    "LifecycleError",
    "LifecycleTransitionError",
    "MissingDatabaseError",
    "MigrationError",
    "ParentDirectoryMissingError",
    "RELATION_DUPLICATE_OF",
    "RELATION_REPLACES",
    "RELATION_SUPERSEDES",
    "RELATION_TYPES",
    "REQUIRED_TABLES",
    "RegistryConflictError",
    "RegistryError",
    "RegistryIntegrityError",
    "RegistryRepository",
    "RegistryValidationError",
    "SCHEMA_SQL",
    "UnknownSchemaVersionError",
    "activate_revision",
    "archive_revision",
    "connect_registry",
    "current_schema_version",
    "foreign_keys_enabled",
    "get_active_revision",
    "get_lifecycle_history",
    "get_relations",
    "get_revision_status",
    "get_schema_version",
    "initialize_registry",
    "make_source_file_id",
    "mark_duplicate",
    "migrate_connection",
    "normalize_db_path",
    "open_registry",
    "production_registry_dir",
    "production_registry_path",
    "register_chunk",
    "register_document_lifecycle",
    "register_document_version",
    "register_source_file",
    "register_subject",
    "register_vector_mapping",
    "registry_transaction",
    "replace_revision",
    "set_revision_status",
    "supersede_revision",
    "transition_matrix",
    "withdraw_revision",
]
